services:

  database:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}"
        ]
      interval: 1s
      timeout: 3s
      retries: 10
    volumes:
      - ./.database_data:/var/lib/postgresql/data
    networks:
      - local

  backend:
    build:
      context: .
      target: prod
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "http://0.0.0.0:8000/healthcheck" ]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - local

networks:
  local:
